[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd server && npm install --production"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "cd server && node src/index.js"
