[build]
builder = "nixpacks"
buildCommand = "cd server && npm install --production"

[deploy]
startCommand = "cd server && node src/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
